const fs = require('fs');
const path = 'backend/src/routes/residents.js';
let text = fs.readFileSync(path, 'utf8');
const regex = /(\s*)\/\/ บันทึก payments เริ่มต้น \(ส่ง monthsVal\)/;
const match = text.match(regex);
if (!match) throw new Error('marker not found');
const indent = match[1];
const insert = `${indent}// ซิงก์ข้อมูลบ้านลงตาราง houses\n${indent}const ownerName = [title, first_name, last_name]\n${indent}  .filter(Boolean)\n${indent}  .map((part) => String(part).trim())\n${indent}  .filter((part) => part.length > 0)\n${indent}  .join(' ') || null;\n${indent}await conn.query(\n${indent}  "INSERT INTO houses (house_number, owner_name, area_sq_m)\\n   VALUES (?, ?, ?)\\n   ON DUPLICATE KEY UPDATE\\n     owner_name = COALESCE(VALUES(owner_name), owner_name),\\n     area_sq_m = COALESCE(VALUES(area_sq_m), area_sq_m)",\n${indent}  [String(house_number), ownerName, area_sq_m != null ? Number(area_sq_m) : null]\n);\n\n${indent}// บันทึก payments เริ่มต้น (ส่ง monthsVal)`;
text = text.replace(regex, insert);
fs.writeFileSync(path, text);
